### ISSUE TITLE
Author "Apertium <capsot>"

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-oci#5]
One of the committers is simply `Apertium <capsot>`. That's not good enough.

I can rewrite the history to say the correct author `Rata Penada <ratapenada@yahoo.com>` or something else, but @Capsot you must also correct your git config so future commits are not from an almost anonymous source.

And after I correct the history, everyone must re-clone the repo.

**Comment by Capsot** [comment]
Hello, I just answered Hèctor about the issue. I noticed it a couple of days ago. I don't know what happened. I always do the same thing. On the other hand I have serious issues with the Box. Some texts I'm working with seem to experience the loss of their end, not much but then some lines disappear. Could anyone tell me what I should change to regain my previous/normal Capsot access? Thank you, have a nice week!

**Comment by TinoDidriksen** [comment]
This has nothing to do with access. This is a local git config issue. You can configure git with what committer name and email it should make commits as - your config is set incorrectly. How to fix this depends on what git client you're using.

If you're using cmdline git, https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup says:
````
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
````

**Comment by Capsot** [comment]
Ok,
Thanks. It seems to work fine now. Take care and have a nice week,
Claudi/Capsot

**Comment by TinoDidriksen** [comment]
So `Capsot <ratapenada@yahoo.com>` is what you want as author? Ok, let me know when I can rewrite history - after which everyone working on this must re-clone the whole repo. This also goes for https://github.com/apertium/apertium-oci-fra (ping @hectoralos).

**Comment by hectoralos** [comment]
For me, it's OK, Tino. You can change the history. I won't make any changes in the files for a while. I guess, this will be for both apertium-oci and apertium-oci-fra. It seems that Capsot has not commit in apertium-fra.

**Comment by Capsot** [comment]
Yes, it is the right name Tino. You can rewrite it right now. I won't add anything until the changes are done!

**Comment by TinoDidriksen** [comment]
Done. apertium-oci and apertium-oci-fra history rewritten - re-clone from scratch.

**Comment by hectoralos** [comment]
Thanks, @TinoDidriksen
