### ISSUE TITLE
texts/Makefile

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-oci#6]
The Makefile does not generate a proper prob-file. I do the following:
In apertium-oci:
`cp texts/oci.unigram.prob oci.prob`
In apertium-oci-fra
```
make
echo "pròva" | apertium -d . oci-fra
```
There isn't any answer to the last command.

**Comment by ftyers** [comment]
@hectoralos sorry I missed this (it was nearly two years ago now). Is it still an issue?

**Comment by hectoralos** [comment]
It seems that it still is an issue. If a take the prob file generated in apertium-oci/texts, I get this:

```
$ cat ../apertium-oci/texts/galaxia.raw.txt | apertium -d . oci-fra
terminate called after throwing an instance of 'DeserialisationException'
  what():  can't deserialise 1 byte integer type: can't deserialise size
Aborted (core dumped)
```

**Comment by ftyers** [comment]
This is a unigram tagger so needs to be used with:
```
      <program name="apertium-tagger -u 2 -g $2">
        <file name="oci-fra.prob"/>
      </program>
```
There are a total of five different tagger formats in Apertium and unfortunately the tagger does not decide between them automatically.
